const char aws_root_ca_pem[] = {"-----BEGIN CERTIFICATE-----\n"
                                "MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF\n"
                                "ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6\n"
                                "b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL\n"
                                "MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv\n"
                                "b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj\n"
                                "ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM\n"
                                "9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw\n"
                                "IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6\n"
                                "VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L\n"
                                "93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm\n"
                                "jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC\n"
                                "AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA\n"
                                "A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI\n"
                                "U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs\n"
                                "N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv\n"
                                "o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU\n"
                                "5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy\n"
                                "rqXRfboQnoZsG4q5WTP468SQvvG5\n"
                                "-----END CERTIFICATE-----"};

const char certificate_pem_crt[] = {"-----BEGIN CERTIFICATE-----\n"
                                    "MIIDWjCCAkKgAwIBAgIVAIE9LT2uqO1zrZ2sNJz1X7aTMHqsMA0GCSqGSIb3DQEB\n"
                                    "CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t\n"
                                    "IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMjA0MTEwNTM4\n"
                                    "NDFaFw00OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAMME0FXUyBJb1QgQ2VydGlmaWNh\n"
                                    "dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDSQOX+qjRvxgmSCtCx\n"
                                    "HuTqr55o/DSHwpR+OkSPOHZL6Fs5/OOuEpmrZnXwT83KEk94SJTm/XD5lEhYDdXj\n"
                                    "eeOY6zDYrW4ukcpAIkNyMlxp03LAjTTay9zFBWx+kYY5bVLJxNRl+W/LcBVq51iw\n"
                                    "4y24Y6qBzZEvoyS1CaphDKWcbi/yZIgyoPog/iC/btfpim6g74qndzLwDD3un0tB\n"
                                    "Y5PZdbIYEEiIJ4Fg7CqalPsuEgWrlvFNGYqDQG0NZwUEisF6yWce/4TynG0MXPVe\n"
                                    "7hqfCcOMGCxjLgwrzzRRTDZ8MTBFBPzagxaFGysroulV4VlPr4sX7e+b8LM1v5uQ\n"
                                    "w/wZAgMBAAGjYDBeMB8GA1UdIwQYMBaAFBpgZ3RLyW0+vOoXoalzQAcpeIKfMB0G\n"
                                    "A1UdDgQWBBRB1cRN8kDqwdOLqjaYkVongd62DzAMBgNVHRMBAf8EAjAAMA4GA1Ud\n"
                                    "DwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEAT1x7DtV2ZvAhRe4sW7cURYk/\n"
                                    "M7TfdN4A7P6hxzNNuq60ijrvm75HmqNCgHwyA/+swDCIYBZhHM4JrVHFCtuCq//V\n"
                                    "D7ed1FYqGNOVIbuWsZnwadh7c+0voZTrrQGZKPfbff12bYYST7yEux4lFQicRyff\n"
                                    "fg5cU9CxO9DQBxZRG3B4Wyn+K+g/yNp4BFZ+4WbWNojyhL3+L/GusfNqJ+X17sgi\n"
                                    "tbX679tOkowWSl+wVj6CYyBcNCXp6zq4iAKEJJg+qmWYKeXHF7p+86G0MJl7M01P\n"
                                    "nYRHuERAkqyFvqYoGX1fTFAAJbBzHx86wIqGRvQavEDM2IgkyEt9U4cfgNrafw==\n"
                                    "-----END CERTIFICATE-----"};

const char private_pem_key[] = {"-----BEGIN RSA PRIVATE KEY-----\n"
                                "MIIEpQIBAAKCAQEA0kDl/qo0b8YJkgrQsR7k6q+eaPw0h8KUfjpEjzh2S+hbOfzj\n"
                                "rhKZq2Z18E/NyhJPeEiU5v1w+ZRIWA3V43njmOsw2K1uLpHKQCJDcjJcadNywI00\n"
                                "2svcxQVsfpGGOW1SycTUZflvy3AVaudYsOMtuGOqgc2RL6MktQmqYQylnG4v8mSI\n"
                                "MqD6IP4gv27X6YpuoO+Kp3cy8Aw97p9LQWOT2XWyGBBIiCeBYOwqmpT7LhIFq5bx\n"
                                "TRmKg0BtDWcFBIrBeslnHv+E8pxtDFz1Xu4anwnDjBgsYy4MK880UUw2fDEwRQT8\n"
                                "2oMWhRsrK6LpVeFZT6+LF+3vm/CzNb+bkMP8GQIDAQABAoIBADCvFFJmiOPEwFyP\n"
                                "ookQtULeTVjT5Tn2RToBNfTPxxyGffEsbG/XILv+apqtb+I1YS9h5xChaLJxslqp\n"
                                "QXh9tcSn2NSjO9sOqP02sdVUce+TJYQObkmnYMRCIEAiZCkR9lR//gpquocpudva\n"
                                "G8BBqkmC0m1h8xdLuGkvBsOYERTqRyc5Rb/wwdF4Y1gQIIJXahoQ/HAPB0GcYdRC\n"
                                "OCuXeD9V78N74hcj0D4AYVmfKraYuStksMDooMiTYj+6zUm/8ukCfUTVuXCxA4zi\n"
                                "+GaIWRFyGjQ1ajTnI4Cp0Iz7A6JaOfC1I95rYysQjrsgpySDvsE6QrSpunNjKEV2\n"
                                "gK2vwG0CgYEA8kJRBZHlbA78akmLcAOr8BoSW8BA7eIThkJ6CxO6teFSDOrvRSP5\n"
                                "bTc5PjI7O3IcpFfMKefCZU7UDWrS7NYit7HGIDIMCSfP1z6ITr3+eNXhd4WrtErY\n"
                                "8/Sk4zjOijhWkHTrn3sgrmBZmFcgXyPjDuQeTJ5a9PPZxr48UUXnUScCgYEA3i3Z\n"
                                "w+TLP3yaktcz2TjAglB9sPxgM/ARQXRfemqQ3S4AZwVJz82M+2r92nmVNaQ/vxaF\n"
                                "7jhb5BVuO3KD8yAyr0Mkz0MjqMKcEDrvo0eqQMVO5q7B7L6lfU2QKA4FpoGZmlkh\n"
                                "q/5YPcJGSsjHZeN3T3tKMHll6vc3PDeQJISEEL8CgYEAkas8qru6lwo/zu1gEb+z\n"
                                "cFFM/qyQnjmVgeKRHf4EA/9zZd8SdqGWBozxN6ven/USseM1GXGJG3+V1GeKYuyz\n"
                                "vX8A4jUVtZ+hwwyPy8FEtYXt5/+RanyjDbXqO9LZppUPwBb940yXLyMyXH7vMSYU\n"
                                "Ds0uRuXlTWsfZPjYrgn5eHsCgYEAnBJPV9mfoOBR4PbFWEESkjgiozIWDkYEiRtL\n"
                                "er3jN0v6QmQnno8BCxf0bQVdeEoB8aTLvjTe8BDR13axFBe5Iv6im+nI4eKbKJeO\n"
                                "AP/1q/wuWcPHPBwMOkJDErAO7hE6Kn+UNLK9n9yZ7iyuTXeFN1MfIYAVxQGWTnml\n"
                                "itF/yBcCgYEA18EgD/agtFgazEoXkVc4tAZ517CuyP5n4tUl3xtbcVRz9rYeonVk\n"
                                "qJ8yXReQq9M1vU+imFx8X8Hn4irFDYpJXVaroHYbuhfhoegXvDRa4UrG6RUBhSsY\n"
                                "+CoZgnAfRv84KYlgCChw/7ofR0D2dSWZhLZ8ySSPGVLB5GFWB9UsCMg=\n"
                                "-----END RSA PRIVATE KEY-----"};